#! /bin/sh

$HOME/.config/polybar/launch.sh
pgrep -x sxhkd > /dev/null || sxhkd &

picom &
~/.fehbg &
xsetroot -cursor_name left_ptr

if [[ $(xrandr -q | grep 'HDMI-2 connected') ]]; then
xrandr --outpu eDP-1 --primary --mode 1920x1080 --rotate normal --output HDMI-2 --mode 1920x1080 --rotate normal --right-of eDP-1
fi



bspc monitor HDMI-2 -d I II III IV V VI VII VIII IX X
bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X





bspc config ignore_ewmh_struts   true

bspc config border_width         3
bspc config window_gap           10
bspc config top_padding          25
bspc config focused_border_color "#7AA2F7"
bspc config normal_border_color "#A9B1Df6"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      truef

bspc config focus_follows_pointer true


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a xdman state=floating
bspc rule -a xdman-Main:\* state=floating
bspc rule -a steam desktop = '^2'